version: '3.8'

services:
  go-service:
    build:
      context: ./score_calculation
      dockerfile: Dockerfile
    ports:
      - "50051:50051"

  fastapi-service:
    build:
      context: ./qnn
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - go-service

