version: '3.8'

services:
  image_processing:
    build: ./image_processing
    volumes:
      - ./image_processing:/app
    depends_on:
      - score_calculation

  score_calculation:
    build: ./score_calculation
    ports:
      - "50051:50051"
