# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import board_pb2 as board__pb2


class BoardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBoard = channel.unary_unary(
                '/proto.BoardService/SendBoard',
                request_serializer=board__pb2.BoardRequest.SerializeToString,
                response_deserializer=board__pb2.ScoreReply.FromString,
                )


class BoardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BoardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBoard,
                    request_deserializer=board__pb2.BoardRequest.FromString,
                    response_serializer=board__pb2.ScoreReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.BoardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BoardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.BoardService/SendBoard',
            board__pb2.BoardRequest.SerializeToString,
            board__pb2.ScoreReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
